spring:
  application:
    name: kafka-consumer

server:
  port: 8084

kafka:
  brokerAddress: localhost:9092
  schemaRegistryAddress: http://localhost:8083
  topics:
    user:
      name: user-topic
      group: userTopicGroup
    company:
      name: company-topic
      group: companyTopicGroup
    message:
      name: message-topic
      group: messageTopicGroup