spring:
  application:
    name: kafka-producer

server:
  port: 8083

kafka:
  brokerAddress: localhost:9092,localhost:9094,localhost:9096
  schemaRegistryAddress: http://localhost:8081
  topics:
    user:
      name: user-topic
    company:
      name: company-topic
    message:
      name: message-topic