spring:
  application:
    name: kafka-producer

server:
  port: 8081

kafka:
  brokerAddress: localhost:9092
  schemaRegistryAddress: http://localhost:8083
  topics:
    user:
      name: user-topic
    company:
      name: company-topic
    message:
      name: message-topic