/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package schema.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroTemperatureAggregate extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4515865716635996563L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroTemperatureAggregate\",\"namespace\":\"schema.avro\",\"fields\":[{\"name\":\"sensorId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"totalTemp\",\"type\":\"double\"},{\"name\":\"count\",\"type\":\"long\"},{\"name\":\"averageTemp\",\"type\":\"double\"},{\"name\":\"windowStart\",\"type\":\"long\"},{\"name\":\"windowEnd\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroTemperatureAggregate> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroTemperatureAggregate> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroTemperatureAggregate> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroTemperatureAggregate> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroTemperatureAggregate> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroTemperatureAggregate to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroTemperatureAggregate from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroTemperatureAggregate instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroTemperatureAggregate fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String sensorId;
  private double totalTemp;
  private long count;
  private double averageTemp;
  private long windowStart;
  private long windowEnd;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroTemperatureAggregate() {}

  /**
   * All-args constructor.
   * @param sensorId The new value for sensorId
   * @param totalTemp The new value for totalTemp
   * @param count The new value for count
   * @param averageTemp The new value for averageTemp
   * @param windowStart The new value for windowStart
   * @param windowEnd The new value for windowEnd
   */
  public AvroTemperatureAggregate(java.lang.String sensorId, java.lang.Double totalTemp, java.lang.Long count, java.lang.Double averageTemp, java.lang.Long windowStart, java.lang.Long windowEnd) {
    this.sensorId = sensorId;
    this.totalTemp = totalTemp;
    this.count = count;
    this.averageTemp = averageTemp;
    this.windowStart = windowStart;
    this.windowEnd = windowEnd;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sensorId;
    case 1: return totalTemp;
    case 2: return count;
    case 3: return averageTemp;
    case 4: return windowStart;
    case 5: return windowEnd;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sensorId = value$ != null ? value$.toString() : null; break;
    case 1: totalTemp = (java.lang.Double)value$; break;
    case 2: count = (java.lang.Long)value$; break;
    case 3: averageTemp = (java.lang.Double)value$; break;
    case 4: windowStart = (java.lang.Long)value$; break;
    case 5: windowEnd = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sensorId' field.
   * @return The value of the 'sensorId' field.
   */
  public java.lang.String getSensorId() {
    return sensorId;
  }


  /**
   * Sets the value of the 'sensorId' field.
   * @param value the value to set.
   */
  public void setSensorId(java.lang.String value) {
    this.sensorId = value;
  }

  /**
   * Gets the value of the 'totalTemp' field.
   * @return The value of the 'totalTemp' field.
   */
  public double getTotalTemp() {
    return totalTemp;
  }


  /**
   * Sets the value of the 'totalTemp' field.
   * @param value the value to set.
   */
  public void setTotalTemp(double value) {
    this.totalTemp = value;
  }

  /**
   * Gets the value of the 'count' field.
   * @return The value of the 'count' field.
   */
  public long getCount() {
    return count;
  }


  /**
   * Sets the value of the 'count' field.
   * @param value the value to set.
   */
  public void setCount(long value) {
    this.count = value;
  }

  /**
   * Gets the value of the 'averageTemp' field.
   * @return The value of the 'averageTemp' field.
   */
  public double getAverageTemp() {
    return averageTemp;
  }


  /**
   * Sets the value of the 'averageTemp' field.
   * @param value the value to set.
   */
  public void setAverageTemp(double value) {
    this.averageTemp = value;
  }

  /**
   * Gets the value of the 'windowStart' field.
   * @return The value of the 'windowStart' field.
   */
  public long getWindowStart() {
    return windowStart;
  }


  /**
   * Sets the value of the 'windowStart' field.
   * @param value the value to set.
   */
  public void setWindowStart(long value) {
    this.windowStart = value;
  }

  /**
   * Gets the value of the 'windowEnd' field.
   * @return The value of the 'windowEnd' field.
   */
  public long getWindowEnd() {
    return windowEnd;
  }


  /**
   * Sets the value of the 'windowEnd' field.
   * @param value the value to set.
   */
  public void setWindowEnd(long value) {
    this.windowEnd = value;
  }

  /**
   * Creates a new AvroTemperatureAggregate RecordBuilder.
   * @return A new AvroTemperatureAggregate RecordBuilder
   */
  public static schema.avro.AvroTemperatureAggregate.Builder newBuilder() {
    return new schema.avro.AvroTemperatureAggregate.Builder();
  }

  /**
   * Creates a new AvroTemperatureAggregate RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroTemperatureAggregate RecordBuilder
   */
  public static schema.avro.AvroTemperatureAggregate.Builder newBuilder(schema.avro.AvroTemperatureAggregate.Builder other) {
    if (other == null) {
      return new schema.avro.AvroTemperatureAggregate.Builder();
    } else {
      return new schema.avro.AvroTemperatureAggregate.Builder(other);
    }
  }

  /**
   * Creates a new AvroTemperatureAggregate RecordBuilder by copying an existing AvroTemperatureAggregate instance.
   * @param other The existing instance to copy.
   * @return A new AvroTemperatureAggregate RecordBuilder
   */
  public static schema.avro.AvroTemperatureAggregate.Builder newBuilder(schema.avro.AvroTemperatureAggregate other) {
    if (other == null) {
      return new schema.avro.AvroTemperatureAggregate.Builder();
    } else {
      return new schema.avro.AvroTemperatureAggregate.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroTemperatureAggregate instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroTemperatureAggregate>
    implements org.apache.avro.data.RecordBuilder<AvroTemperatureAggregate> {

    private java.lang.String sensorId;
    private double totalTemp;
    private long count;
    private double averageTemp;
    private long windowStart;
    private long windowEnd;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(schema.avro.AvroTemperatureAggregate.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sensorId)) {
        this.sensorId = data().deepCopy(fields()[0].schema(), other.sensorId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.totalTemp)) {
        this.totalTemp = data().deepCopy(fields()[1].schema(), other.totalTemp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.count)) {
        this.count = data().deepCopy(fields()[2].schema(), other.count);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.averageTemp)) {
        this.averageTemp = data().deepCopy(fields()[3].schema(), other.averageTemp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.windowStart)) {
        this.windowStart = data().deepCopy(fields()[4].schema(), other.windowStart);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.windowEnd)) {
        this.windowEnd = data().deepCopy(fields()[5].schema(), other.windowEnd);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroTemperatureAggregate instance
     * @param other The existing instance to copy.
     */
    private Builder(schema.avro.AvroTemperatureAggregate other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.sensorId)) {
        this.sensorId = data().deepCopy(fields()[0].schema(), other.sensorId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.totalTemp)) {
        this.totalTemp = data().deepCopy(fields()[1].schema(), other.totalTemp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.count)) {
        this.count = data().deepCopy(fields()[2].schema(), other.count);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.averageTemp)) {
        this.averageTemp = data().deepCopy(fields()[3].schema(), other.averageTemp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.windowStart)) {
        this.windowStart = data().deepCopy(fields()[4].schema(), other.windowStart);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.windowEnd)) {
        this.windowEnd = data().deepCopy(fields()[5].schema(), other.windowEnd);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'sensorId' field.
      * @return The value.
      */
    public java.lang.String getSensorId() {
      return sensorId;
    }


    /**
      * Sets the value of the 'sensorId' field.
      * @param value The value of 'sensorId'.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureAggregate.Builder setSensorId(java.lang.String value) {
      validate(fields()[0], value);
      this.sensorId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sensorId' field has been set.
      * @return True if the 'sensorId' field has been set, false otherwise.
      */
    public boolean hasSensorId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sensorId' field.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureAggregate.Builder clearSensorId() {
      sensorId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalTemp' field.
      * @return The value.
      */
    public double getTotalTemp() {
      return totalTemp;
    }


    /**
      * Sets the value of the 'totalTemp' field.
      * @param value The value of 'totalTemp'.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureAggregate.Builder setTotalTemp(double value) {
      validate(fields()[1], value);
      this.totalTemp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'totalTemp' field has been set.
      * @return True if the 'totalTemp' field has been set, false otherwise.
      */
    public boolean hasTotalTemp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'totalTemp' field.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureAggregate.Builder clearTotalTemp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'count' field.
      * @return The value.
      */
    public long getCount() {
      return count;
    }


    /**
      * Sets the value of the 'count' field.
      * @param value The value of 'count'.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureAggregate.Builder setCount(long value) {
      validate(fields()[2], value);
      this.count = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'count' field has been set.
      * @return True if the 'count' field has been set, false otherwise.
      */
    public boolean hasCount() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'count' field.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureAggregate.Builder clearCount() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'averageTemp' field.
      * @return The value.
      */
    public double getAverageTemp() {
      return averageTemp;
    }


    /**
      * Sets the value of the 'averageTemp' field.
      * @param value The value of 'averageTemp'.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureAggregate.Builder setAverageTemp(double value) {
      validate(fields()[3], value);
      this.averageTemp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'averageTemp' field has been set.
      * @return True if the 'averageTemp' field has been set, false otherwise.
      */
    public boolean hasAverageTemp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'averageTemp' field.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureAggregate.Builder clearAverageTemp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'windowStart' field.
      * @return The value.
      */
    public long getWindowStart() {
      return windowStart;
    }


    /**
      * Sets the value of the 'windowStart' field.
      * @param value The value of 'windowStart'.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureAggregate.Builder setWindowStart(long value) {
      validate(fields()[4], value);
      this.windowStart = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'windowStart' field has been set.
      * @return True if the 'windowStart' field has been set, false otherwise.
      */
    public boolean hasWindowStart() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'windowStart' field.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureAggregate.Builder clearWindowStart() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'windowEnd' field.
      * @return The value.
      */
    public long getWindowEnd() {
      return windowEnd;
    }


    /**
      * Sets the value of the 'windowEnd' field.
      * @param value The value of 'windowEnd'.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureAggregate.Builder setWindowEnd(long value) {
      validate(fields()[5], value);
      this.windowEnd = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'windowEnd' field has been set.
      * @return True if the 'windowEnd' field has been set, false otherwise.
      */
    public boolean hasWindowEnd() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'windowEnd' field.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureAggregate.Builder clearWindowEnd() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroTemperatureAggregate build() {
      try {
        AvroTemperatureAggregate record = new AvroTemperatureAggregate();
        record.sensorId = fieldSetFlags()[0] ? this.sensorId : (java.lang.String) defaultValue(fields()[0]);
        record.totalTemp = fieldSetFlags()[1] ? this.totalTemp : (java.lang.Double) defaultValue(fields()[1]);
        record.count = fieldSetFlags()[2] ? this.count : (java.lang.Long) defaultValue(fields()[2]);
        record.averageTemp = fieldSetFlags()[3] ? this.averageTemp : (java.lang.Double) defaultValue(fields()[3]);
        record.windowStart = fieldSetFlags()[4] ? this.windowStart : (java.lang.Long) defaultValue(fields()[4]);
        record.windowEnd = fieldSetFlags()[5] ? this.windowEnd : (java.lang.Long) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroTemperatureAggregate>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroTemperatureAggregate>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroTemperatureAggregate>
    READER$ = (org.apache.avro.io.DatumReader<AvroTemperatureAggregate>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.sensorId);

    out.writeDouble(this.totalTemp);

    out.writeLong(this.count);

    out.writeDouble(this.averageTemp);

    out.writeLong(this.windowStart);

    out.writeLong(this.windowEnd);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.sensorId = in.readString();

      this.totalTemp = in.readDouble();

      this.count = in.readLong();

      this.averageTemp = in.readDouble();

      this.windowStart = in.readLong();

      this.windowEnd = in.readLong();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.sensorId = in.readString();
          break;

        case 1:
          this.totalTemp = in.readDouble();
          break;

        case 2:
          this.count = in.readLong();
          break;

        case 3:
          this.averageTemp = in.readDouble();
          break;

        case 4:
          this.windowStart = in.readLong();
          break;

        case 5:
          this.windowEnd = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










