/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package schema.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroCompanyStats extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9177090434320339031L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroCompanyStats\",\"namespace\":\"schema.avro\",\"fields\":[{\"name\":\"companyId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"headcount\",\"type\":\"int\",\"default\":0},{\"name\":\"totalSalary\",\"type\":\"double\",\"default\":0.0},{\"name\":\"averageSalary\",\"type\":\"double\",\"default\":0.0},{\"name\":\"activeCount\",\"type\":\"int\",\"default\":0},{\"name\":\"inactiveCount\",\"type\":\"int\",\"default\":0},{\"name\":\"engineeringCount\",\"type\":\"int\",\"default\":0},{\"name\":\"hrCount\",\"type\":\"int\",\"default\":0},{\"name\":\"salesCount\",\"type\":\"int\",\"default\":0},{\"name\":\"financeCount\",\"type\":\"int\",\"default\":0},{\"name\":\"lastUpdatedAt\",\"type\":\"long\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroCompanyStats> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroCompanyStats> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroCompanyStats> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroCompanyStats> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroCompanyStats> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroCompanyStats to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroCompanyStats from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroCompanyStats instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroCompanyStats fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String companyId;
  private int headcount;
  private double totalSalary;
  private double averageSalary;
  private int activeCount;
  private int inactiveCount;
  private int engineeringCount;
  private int hrCount;
  private int salesCount;
  private int financeCount;
  private long lastUpdatedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroCompanyStats() {}

  /**
   * All-args constructor.
   * @param companyId The new value for companyId
   * @param headcount The new value for headcount
   * @param totalSalary The new value for totalSalary
   * @param averageSalary The new value for averageSalary
   * @param activeCount The new value for activeCount
   * @param inactiveCount The new value for inactiveCount
   * @param engineeringCount The new value for engineeringCount
   * @param hrCount The new value for hrCount
   * @param salesCount The new value for salesCount
   * @param financeCount The new value for financeCount
   * @param lastUpdatedAt The new value for lastUpdatedAt
   */
  public AvroCompanyStats(java.lang.String companyId, java.lang.Integer headcount, java.lang.Double totalSalary, java.lang.Double averageSalary, java.lang.Integer activeCount, java.lang.Integer inactiveCount, java.lang.Integer engineeringCount, java.lang.Integer hrCount, java.lang.Integer salesCount, java.lang.Integer financeCount, java.lang.Long lastUpdatedAt) {
    this.companyId = companyId;
    this.headcount = headcount;
    this.totalSalary = totalSalary;
    this.averageSalary = averageSalary;
    this.activeCount = activeCount;
    this.inactiveCount = inactiveCount;
    this.engineeringCount = engineeringCount;
    this.hrCount = hrCount;
    this.salesCount = salesCount;
    this.financeCount = financeCount;
    this.lastUpdatedAt = lastUpdatedAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return companyId;
    case 1: return headcount;
    case 2: return totalSalary;
    case 3: return averageSalary;
    case 4: return activeCount;
    case 5: return inactiveCount;
    case 6: return engineeringCount;
    case 7: return hrCount;
    case 8: return salesCount;
    case 9: return financeCount;
    case 10: return lastUpdatedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: companyId = value$ != null ? value$.toString() : null; break;
    case 1: headcount = (java.lang.Integer)value$; break;
    case 2: totalSalary = (java.lang.Double)value$; break;
    case 3: averageSalary = (java.lang.Double)value$; break;
    case 4: activeCount = (java.lang.Integer)value$; break;
    case 5: inactiveCount = (java.lang.Integer)value$; break;
    case 6: engineeringCount = (java.lang.Integer)value$; break;
    case 7: hrCount = (java.lang.Integer)value$; break;
    case 8: salesCount = (java.lang.Integer)value$; break;
    case 9: financeCount = (java.lang.Integer)value$; break;
    case 10: lastUpdatedAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'companyId' field.
   * @return The value of the 'companyId' field.
   */
  public java.lang.String getCompanyId() {
    return companyId;
  }


  /**
   * Sets the value of the 'companyId' field.
   * @param value the value to set.
   */
  public void setCompanyId(java.lang.String value) {
    this.companyId = value;
  }

  /**
   * Gets the value of the 'headcount' field.
   * @return The value of the 'headcount' field.
   */
  public int getHeadcount() {
    return headcount;
  }


  /**
   * Sets the value of the 'headcount' field.
   * @param value the value to set.
   */
  public void setHeadcount(int value) {
    this.headcount = value;
  }

  /**
   * Gets the value of the 'totalSalary' field.
   * @return The value of the 'totalSalary' field.
   */
  public double getTotalSalary() {
    return totalSalary;
  }


  /**
   * Sets the value of the 'totalSalary' field.
   * @param value the value to set.
   */
  public void setTotalSalary(double value) {
    this.totalSalary = value;
  }

  /**
   * Gets the value of the 'averageSalary' field.
   * @return The value of the 'averageSalary' field.
   */
  public double getAverageSalary() {
    return averageSalary;
  }


  /**
   * Sets the value of the 'averageSalary' field.
   * @param value the value to set.
   */
  public void setAverageSalary(double value) {
    this.averageSalary = value;
  }

  /**
   * Gets the value of the 'activeCount' field.
   * @return The value of the 'activeCount' field.
   */
  public int getActiveCount() {
    return activeCount;
  }


  /**
   * Sets the value of the 'activeCount' field.
   * @param value the value to set.
   */
  public void setActiveCount(int value) {
    this.activeCount = value;
  }

  /**
   * Gets the value of the 'inactiveCount' field.
   * @return The value of the 'inactiveCount' field.
   */
  public int getInactiveCount() {
    return inactiveCount;
  }


  /**
   * Sets the value of the 'inactiveCount' field.
   * @param value the value to set.
   */
  public void setInactiveCount(int value) {
    this.inactiveCount = value;
  }

  /**
   * Gets the value of the 'engineeringCount' field.
   * @return The value of the 'engineeringCount' field.
   */
  public int getEngineeringCount() {
    return engineeringCount;
  }


  /**
   * Sets the value of the 'engineeringCount' field.
   * @param value the value to set.
   */
  public void setEngineeringCount(int value) {
    this.engineeringCount = value;
  }

  /**
   * Gets the value of the 'hrCount' field.
   * @return The value of the 'hrCount' field.
   */
  public int getHrCount() {
    return hrCount;
  }


  /**
   * Sets the value of the 'hrCount' field.
   * @param value the value to set.
   */
  public void setHrCount(int value) {
    this.hrCount = value;
  }

  /**
   * Gets the value of the 'salesCount' field.
   * @return The value of the 'salesCount' field.
   */
  public int getSalesCount() {
    return salesCount;
  }


  /**
   * Sets the value of the 'salesCount' field.
   * @param value the value to set.
   */
  public void setSalesCount(int value) {
    this.salesCount = value;
  }

  /**
   * Gets the value of the 'financeCount' field.
   * @return The value of the 'financeCount' field.
   */
  public int getFinanceCount() {
    return financeCount;
  }


  /**
   * Sets the value of the 'financeCount' field.
   * @param value the value to set.
   */
  public void setFinanceCount(int value) {
    this.financeCount = value;
  }

  /**
   * Gets the value of the 'lastUpdatedAt' field.
   * @return The value of the 'lastUpdatedAt' field.
   */
  public long getLastUpdatedAt() {
    return lastUpdatedAt;
  }


  /**
   * Sets the value of the 'lastUpdatedAt' field.
   * @param value the value to set.
   */
  public void setLastUpdatedAt(long value) {
    this.lastUpdatedAt = value;
  }

  /**
   * Creates a new AvroCompanyStats RecordBuilder.
   * @return A new AvroCompanyStats RecordBuilder
   */
  public static schema.avro.AvroCompanyStats.Builder newBuilder() {
    return new schema.avro.AvroCompanyStats.Builder();
  }

  /**
   * Creates a new AvroCompanyStats RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroCompanyStats RecordBuilder
   */
  public static schema.avro.AvroCompanyStats.Builder newBuilder(schema.avro.AvroCompanyStats.Builder other) {
    if (other == null) {
      return new schema.avro.AvroCompanyStats.Builder();
    } else {
      return new schema.avro.AvroCompanyStats.Builder(other);
    }
  }

  /**
   * Creates a new AvroCompanyStats RecordBuilder by copying an existing AvroCompanyStats instance.
   * @param other The existing instance to copy.
   * @return A new AvroCompanyStats RecordBuilder
   */
  public static schema.avro.AvroCompanyStats.Builder newBuilder(schema.avro.AvroCompanyStats other) {
    if (other == null) {
      return new schema.avro.AvroCompanyStats.Builder();
    } else {
      return new schema.avro.AvroCompanyStats.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroCompanyStats instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroCompanyStats>
    implements org.apache.avro.data.RecordBuilder<AvroCompanyStats> {

    private java.lang.String companyId;
    private int headcount;
    private double totalSalary;
    private double averageSalary;
    private int activeCount;
    private int inactiveCount;
    private int engineeringCount;
    private int hrCount;
    private int salesCount;
    private int financeCount;
    private long lastUpdatedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(schema.avro.AvroCompanyStats.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.companyId)) {
        this.companyId = data().deepCopy(fields()[0].schema(), other.companyId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.headcount)) {
        this.headcount = data().deepCopy(fields()[1].schema(), other.headcount);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.totalSalary)) {
        this.totalSalary = data().deepCopy(fields()[2].schema(), other.totalSalary);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.averageSalary)) {
        this.averageSalary = data().deepCopy(fields()[3].schema(), other.averageSalary);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.activeCount)) {
        this.activeCount = data().deepCopy(fields()[4].schema(), other.activeCount);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.inactiveCount)) {
        this.inactiveCount = data().deepCopy(fields()[5].schema(), other.inactiveCount);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.engineeringCount)) {
        this.engineeringCount = data().deepCopy(fields()[6].schema(), other.engineeringCount);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.hrCount)) {
        this.hrCount = data().deepCopy(fields()[7].schema(), other.hrCount);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.salesCount)) {
        this.salesCount = data().deepCopy(fields()[8].schema(), other.salesCount);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.financeCount)) {
        this.financeCount = data().deepCopy(fields()[9].schema(), other.financeCount);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.lastUpdatedAt)) {
        this.lastUpdatedAt = data().deepCopy(fields()[10].schema(), other.lastUpdatedAt);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroCompanyStats instance
     * @param other The existing instance to copy.
     */
    private Builder(schema.avro.AvroCompanyStats other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.companyId)) {
        this.companyId = data().deepCopy(fields()[0].schema(), other.companyId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.headcount)) {
        this.headcount = data().deepCopy(fields()[1].schema(), other.headcount);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.totalSalary)) {
        this.totalSalary = data().deepCopy(fields()[2].schema(), other.totalSalary);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.averageSalary)) {
        this.averageSalary = data().deepCopy(fields()[3].schema(), other.averageSalary);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.activeCount)) {
        this.activeCount = data().deepCopy(fields()[4].schema(), other.activeCount);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.inactiveCount)) {
        this.inactiveCount = data().deepCopy(fields()[5].schema(), other.inactiveCount);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.engineeringCount)) {
        this.engineeringCount = data().deepCopy(fields()[6].schema(), other.engineeringCount);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.hrCount)) {
        this.hrCount = data().deepCopy(fields()[7].schema(), other.hrCount);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.salesCount)) {
        this.salesCount = data().deepCopy(fields()[8].schema(), other.salesCount);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.financeCount)) {
        this.financeCount = data().deepCopy(fields()[9].schema(), other.financeCount);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.lastUpdatedAt)) {
        this.lastUpdatedAt = data().deepCopy(fields()[10].schema(), other.lastUpdatedAt);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'companyId' field.
      * @return The value.
      */
    public java.lang.String getCompanyId() {
      return companyId;
    }


    /**
      * Sets the value of the 'companyId' field.
      * @param value The value of 'companyId'.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder setCompanyId(java.lang.String value) {
      validate(fields()[0], value);
      this.companyId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'companyId' field has been set.
      * @return True if the 'companyId' field has been set, false otherwise.
      */
    public boolean hasCompanyId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'companyId' field.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder clearCompanyId() {
      companyId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'headcount' field.
      * @return The value.
      */
    public int getHeadcount() {
      return headcount;
    }


    /**
      * Sets the value of the 'headcount' field.
      * @param value The value of 'headcount'.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder setHeadcount(int value) {
      validate(fields()[1], value);
      this.headcount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'headcount' field has been set.
      * @return True if the 'headcount' field has been set, false otherwise.
      */
    public boolean hasHeadcount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'headcount' field.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder clearHeadcount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalSalary' field.
      * @return The value.
      */
    public double getTotalSalary() {
      return totalSalary;
    }


    /**
      * Sets the value of the 'totalSalary' field.
      * @param value The value of 'totalSalary'.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder setTotalSalary(double value) {
      validate(fields()[2], value);
      this.totalSalary = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'totalSalary' field has been set.
      * @return True if the 'totalSalary' field has been set, false otherwise.
      */
    public boolean hasTotalSalary() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'totalSalary' field.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder clearTotalSalary() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'averageSalary' field.
      * @return The value.
      */
    public double getAverageSalary() {
      return averageSalary;
    }


    /**
      * Sets the value of the 'averageSalary' field.
      * @param value The value of 'averageSalary'.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder setAverageSalary(double value) {
      validate(fields()[3], value);
      this.averageSalary = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'averageSalary' field has been set.
      * @return True if the 'averageSalary' field has been set, false otherwise.
      */
    public boolean hasAverageSalary() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'averageSalary' field.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder clearAverageSalary() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'activeCount' field.
      * @return The value.
      */
    public int getActiveCount() {
      return activeCount;
    }


    /**
      * Sets the value of the 'activeCount' field.
      * @param value The value of 'activeCount'.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder setActiveCount(int value) {
      validate(fields()[4], value);
      this.activeCount = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'activeCount' field has been set.
      * @return True if the 'activeCount' field has been set, false otherwise.
      */
    public boolean hasActiveCount() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'activeCount' field.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder clearActiveCount() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'inactiveCount' field.
      * @return The value.
      */
    public int getInactiveCount() {
      return inactiveCount;
    }


    /**
      * Sets the value of the 'inactiveCount' field.
      * @param value The value of 'inactiveCount'.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder setInactiveCount(int value) {
      validate(fields()[5], value);
      this.inactiveCount = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'inactiveCount' field has been set.
      * @return True if the 'inactiveCount' field has been set, false otherwise.
      */
    public boolean hasInactiveCount() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'inactiveCount' field.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder clearInactiveCount() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'engineeringCount' field.
      * @return The value.
      */
    public int getEngineeringCount() {
      return engineeringCount;
    }


    /**
      * Sets the value of the 'engineeringCount' field.
      * @param value The value of 'engineeringCount'.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder setEngineeringCount(int value) {
      validate(fields()[6], value);
      this.engineeringCount = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'engineeringCount' field has been set.
      * @return True if the 'engineeringCount' field has been set, false otherwise.
      */
    public boolean hasEngineeringCount() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'engineeringCount' field.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder clearEngineeringCount() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'hrCount' field.
      * @return The value.
      */
    public int getHrCount() {
      return hrCount;
    }


    /**
      * Sets the value of the 'hrCount' field.
      * @param value The value of 'hrCount'.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder setHrCount(int value) {
      validate(fields()[7], value);
      this.hrCount = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'hrCount' field has been set.
      * @return True if the 'hrCount' field has been set, false otherwise.
      */
    public boolean hasHrCount() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'hrCount' field.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder clearHrCount() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'salesCount' field.
      * @return The value.
      */
    public int getSalesCount() {
      return salesCount;
    }


    /**
      * Sets the value of the 'salesCount' field.
      * @param value The value of 'salesCount'.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder setSalesCount(int value) {
      validate(fields()[8], value);
      this.salesCount = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'salesCount' field has been set.
      * @return True if the 'salesCount' field has been set, false otherwise.
      */
    public boolean hasSalesCount() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'salesCount' field.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder clearSalesCount() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'financeCount' field.
      * @return The value.
      */
    public int getFinanceCount() {
      return financeCount;
    }


    /**
      * Sets the value of the 'financeCount' field.
      * @param value The value of 'financeCount'.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder setFinanceCount(int value) {
      validate(fields()[9], value);
      this.financeCount = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'financeCount' field has been set.
      * @return True if the 'financeCount' field has been set, false otherwise.
      */
    public boolean hasFinanceCount() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'financeCount' field.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder clearFinanceCount() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastUpdatedAt' field.
      * @return The value.
      */
    public long getLastUpdatedAt() {
      return lastUpdatedAt;
    }


    /**
      * Sets the value of the 'lastUpdatedAt' field.
      * @param value The value of 'lastUpdatedAt'.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder setLastUpdatedAt(long value) {
      validate(fields()[10], value);
      this.lastUpdatedAt = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'lastUpdatedAt' field has been set.
      * @return True if the 'lastUpdatedAt' field has been set, false otherwise.
      */
    public boolean hasLastUpdatedAt() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'lastUpdatedAt' field.
      * @return This builder.
      */
    public schema.avro.AvroCompanyStats.Builder clearLastUpdatedAt() {
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroCompanyStats build() {
      try {
        AvroCompanyStats record = new AvroCompanyStats();
        record.companyId = fieldSetFlags()[0] ? this.companyId : (java.lang.String) defaultValue(fields()[0]);
        record.headcount = fieldSetFlags()[1] ? this.headcount : (java.lang.Integer) defaultValue(fields()[1]);
        record.totalSalary = fieldSetFlags()[2] ? this.totalSalary : (java.lang.Double) defaultValue(fields()[2]);
        record.averageSalary = fieldSetFlags()[3] ? this.averageSalary : (java.lang.Double) defaultValue(fields()[3]);
        record.activeCount = fieldSetFlags()[4] ? this.activeCount : (java.lang.Integer) defaultValue(fields()[4]);
        record.inactiveCount = fieldSetFlags()[5] ? this.inactiveCount : (java.lang.Integer) defaultValue(fields()[5]);
        record.engineeringCount = fieldSetFlags()[6] ? this.engineeringCount : (java.lang.Integer) defaultValue(fields()[6]);
        record.hrCount = fieldSetFlags()[7] ? this.hrCount : (java.lang.Integer) defaultValue(fields()[7]);
        record.salesCount = fieldSetFlags()[8] ? this.salesCount : (java.lang.Integer) defaultValue(fields()[8]);
        record.financeCount = fieldSetFlags()[9] ? this.financeCount : (java.lang.Integer) defaultValue(fields()[9]);
        record.lastUpdatedAt = fieldSetFlags()[10] ? this.lastUpdatedAt : (java.lang.Long) defaultValue(fields()[10]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroCompanyStats>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroCompanyStats>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroCompanyStats>
    READER$ = (org.apache.avro.io.DatumReader<AvroCompanyStats>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.companyId);

    out.writeInt(this.headcount);

    out.writeDouble(this.totalSalary);

    out.writeDouble(this.averageSalary);

    out.writeInt(this.activeCount);

    out.writeInt(this.inactiveCount);

    out.writeInt(this.engineeringCount);

    out.writeInt(this.hrCount);

    out.writeInt(this.salesCount);

    out.writeInt(this.financeCount);

    out.writeLong(this.lastUpdatedAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.companyId = in.readString();

      this.headcount = in.readInt();

      this.totalSalary = in.readDouble();

      this.averageSalary = in.readDouble();

      this.activeCount = in.readInt();

      this.inactiveCount = in.readInt();

      this.engineeringCount = in.readInt();

      this.hrCount = in.readInt();

      this.salesCount = in.readInt();

      this.financeCount = in.readInt();

      this.lastUpdatedAt = in.readLong();

    } else {
      for (int i = 0; i < 11; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.companyId = in.readString();
          break;

        case 1:
          this.headcount = in.readInt();
          break;

        case 2:
          this.totalSalary = in.readDouble();
          break;

        case 3:
          this.averageSalary = in.readDouble();
          break;

        case 4:
          this.activeCount = in.readInt();
          break;

        case 5:
          this.inactiveCount = in.readInt();
          break;

        case 6:
          this.engineeringCount = in.readInt();
          break;

        case 7:
          this.hrCount = in.readInt();
          break;

        case 8:
          this.salesCount = in.readInt();
          break;

        case 9:
          this.financeCount = in.readInt();
          break;

        case 10:
          this.lastUpdatedAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










