/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package schema.avro;
@org.apache.avro.specific.AvroGenerated
public enum UserStatus implements org.apache.avro.generic.GenericEnumSymbol<UserStatus> {
  ACTIVE, INACTIVE, TERMINATED, ON_LEAVE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UserStatus\",\"namespace\":\"schema.avro\",\"symbols\":[\"ACTIVE\",\"INACTIVE\",\"TERMINATED\",\"ON_LEAVE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
