spring.application.name=streams
server.port=8082
spring.kafka.bootstrap-servers=localhost:9092,localhost:9094,localhost:9096
spring.kafka.streams.application-id=user-processing-app
spring.kafka.streams.properties.processing.guarantee=exactly_once_v2
spring.kafka.streams.properties.commit.interval.ms=1000
spring.kafka.streams.properties.num.standby.replicas=1
spring.kafka.streams.properties.replication.factor=3
spring.kafka.streams.properties.schema.registry.url=http://localhost:8081
spring.kafka.streams.properties.isolation.level=read_committed
spring.kafka.streams.properties.max.poll.records=500
spring.kafka.topics.user.name=user-topic
spring.kafka.topics.company.name=company-topic
spring.kafka.topics.message.name=message-topic
spring.kafka.topics.company.statistics=company-stats-topic