spring.application.name=streams
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.streams.application-id=user-processing-app
spring.kafka.streams.properties.processing.guarantee=exactly_once_v2
spring.kafka.streams.properties.commit.interval.ms=1000
spring.kafka.streams.properties.num.standby.replicas=1
spring.kafka.streams.properties.replication.factor=3
spring.kafka.topics.user.name=user-topic
server.port=8082