/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package schema.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroCompany extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5599843752140153806L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroCompany\",\"namespace\":\"schema.avro\",\"fields\":[{\"name\":\"companyId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Required - partition key\"},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Required\"},{\"name\":\"industry\",\"type\":{\"type\":\"enum\",\"name\":\"Industry\",\"symbols\":[\"TECH\",\"FINANCE\",\"HEALTH\",\"OTHER\"]},\"doc\":\"Required\"},{\"name\":\"country\",\"type\":{\"type\":\"enum\",\"name\":\"Country\",\"symbols\":[\"IN\",\"US\",\"UK\",\"OTHER\"]},\"doc\":\"Required\"},{\"name\":\"address\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Optional\",\"default\":null},{\"name\":\"employeeCount\",\"type\":[\"null\",\"int\"],\"doc\":\"Optional - not all integrations provide this\",\"default\":null},{\"name\":\"revenue\",\"type\":[\"null\",\"double\"],\"doc\":\"Optional\",\"default\":null},{\"name\":\"updatedAt\",\"type\":\"long\",\"doc\":\"Required - epoch millis\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroCompany> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroCompany> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroCompany> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroCompany> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroCompany> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroCompany to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroCompany from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroCompany instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroCompany fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Required - partition key */
  private java.lang.String companyId;
  /** Required */
  private java.lang.String name;
  /** Required */
  private schema.avro.Industry industry;
  /** Required */
  private schema.avro.Country country;
  /** Optional */
  private java.lang.String address;
  /** Optional - not all integrations provide this */
  private java.lang.Integer employeeCount;
  /** Optional */
  private java.lang.Double revenue;
  /** Required - epoch millis */
  private long updatedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroCompany() {}

  /**
   * All-args constructor.
   * @param companyId Required - partition key
   * @param name Required
   * @param industry Required
   * @param country Required
   * @param address Optional
   * @param employeeCount Optional - not all integrations provide this
   * @param revenue Optional
   * @param updatedAt Required - epoch millis
   */
  public AvroCompany(java.lang.String companyId, java.lang.String name, schema.avro.Industry industry, schema.avro.Country country, java.lang.String address, java.lang.Integer employeeCount, java.lang.Double revenue, java.lang.Long updatedAt) {
    this.companyId = companyId;
    this.name = name;
    this.industry = industry;
    this.country = country;
    this.address = address;
    this.employeeCount = employeeCount;
    this.revenue = revenue;
    this.updatedAt = updatedAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return companyId;
    case 1: return name;
    case 2: return industry;
    case 3: return country;
    case 4: return address;
    case 5: return employeeCount;
    case 6: return revenue;
    case 7: return updatedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: companyId = value$ != null ? value$.toString() : null; break;
    case 1: name = value$ != null ? value$.toString() : null; break;
    case 2: industry = (schema.avro.Industry)value$; break;
    case 3: country = (schema.avro.Country)value$; break;
    case 4: address = value$ != null ? value$.toString() : null; break;
    case 5: employeeCount = (java.lang.Integer)value$; break;
    case 6: revenue = (java.lang.Double)value$; break;
    case 7: updatedAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'companyId' field.
   * @return Required - partition key
   */
  public java.lang.String getCompanyId() {
    return companyId;
  }


  /**
   * Sets the value of the 'companyId' field.
   * Required - partition key
   * @param value the value to set.
   */
  public void setCompanyId(java.lang.String value) {
    this.companyId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return Required
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * Required
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'industry' field.
   * @return Required
   */
  public schema.avro.Industry getIndustry() {
    return industry;
  }


  /**
   * Sets the value of the 'industry' field.
   * Required
   * @param value the value to set.
   */
  public void setIndustry(schema.avro.Industry value) {
    this.industry = value;
  }

  /**
   * Gets the value of the 'country' field.
   * @return Required
   */
  public schema.avro.Country getCountry() {
    return country;
  }


  /**
   * Sets the value of the 'country' field.
   * Required
   * @param value the value to set.
   */
  public void setCountry(schema.avro.Country value) {
    this.country = value;
  }

  /**
   * Gets the value of the 'address' field.
   * @return Optional
   */
  public java.lang.String getAddress() {
    return address;
  }


  /**
   * Sets the value of the 'address' field.
   * Optional
   * @param value the value to set.
   */
  public void setAddress(java.lang.String value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'employeeCount' field.
   * @return Optional - not all integrations provide this
   */
  public java.lang.Integer getEmployeeCount() {
    return employeeCount;
  }


  /**
   * Sets the value of the 'employeeCount' field.
   * Optional - not all integrations provide this
   * @param value the value to set.
   */
  public void setEmployeeCount(java.lang.Integer value) {
    this.employeeCount = value;
  }

  /**
   * Gets the value of the 'revenue' field.
   * @return Optional
   */
  public java.lang.Double getRevenue() {
    return revenue;
  }


  /**
   * Sets the value of the 'revenue' field.
   * Optional
   * @param value the value to set.
   */
  public void setRevenue(java.lang.Double value) {
    this.revenue = value;
  }

  /**
   * Gets the value of the 'updatedAt' field.
   * @return Required - epoch millis
   */
  public long getUpdatedAt() {
    return updatedAt;
  }


  /**
   * Sets the value of the 'updatedAt' field.
   * Required - epoch millis
   * @param value the value to set.
   */
  public void setUpdatedAt(long value) {
    this.updatedAt = value;
  }

  /**
   * Creates a new AvroCompany RecordBuilder.
   * @return A new AvroCompany RecordBuilder
   */
  public static schema.avro.AvroCompany.Builder newBuilder() {
    return new schema.avro.AvroCompany.Builder();
  }

  /**
   * Creates a new AvroCompany RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroCompany RecordBuilder
   */
  public static schema.avro.AvroCompany.Builder newBuilder(schema.avro.AvroCompany.Builder other) {
    if (other == null) {
      return new schema.avro.AvroCompany.Builder();
    } else {
      return new schema.avro.AvroCompany.Builder(other);
    }
  }

  /**
   * Creates a new AvroCompany RecordBuilder by copying an existing AvroCompany instance.
   * @param other The existing instance to copy.
   * @return A new AvroCompany RecordBuilder
   */
  public static schema.avro.AvroCompany.Builder newBuilder(schema.avro.AvroCompany other) {
    if (other == null) {
      return new schema.avro.AvroCompany.Builder();
    } else {
      return new schema.avro.AvroCompany.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroCompany instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroCompany>
    implements org.apache.avro.data.RecordBuilder<AvroCompany> {

    /** Required - partition key */
    private java.lang.String companyId;
    /** Required */
    private java.lang.String name;
    /** Required */
    private schema.avro.Industry industry;
    /** Required */
    private schema.avro.Country country;
    /** Optional */
    private java.lang.String address;
    /** Optional - not all integrations provide this */
    private java.lang.Integer employeeCount;
    /** Optional */
    private java.lang.Double revenue;
    /** Required - epoch millis */
    private long updatedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(schema.avro.AvroCompany.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.companyId)) {
        this.companyId = data().deepCopy(fields()[0].schema(), other.companyId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.industry)) {
        this.industry = data().deepCopy(fields()[2].schema(), other.industry);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.country)) {
        this.country = data().deepCopy(fields()[3].schema(), other.country);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.address)) {
        this.address = data().deepCopy(fields()[4].schema(), other.address);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.employeeCount)) {
        this.employeeCount = data().deepCopy(fields()[5].schema(), other.employeeCount);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.revenue)) {
        this.revenue = data().deepCopy(fields()[6].schema(), other.revenue);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[7].schema(), other.updatedAt);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroCompany instance
     * @param other The existing instance to copy.
     */
    private Builder(schema.avro.AvroCompany other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.companyId)) {
        this.companyId = data().deepCopy(fields()[0].schema(), other.companyId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.industry)) {
        this.industry = data().deepCopy(fields()[2].schema(), other.industry);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.country)) {
        this.country = data().deepCopy(fields()[3].schema(), other.country);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.address)) {
        this.address = data().deepCopy(fields()[4].schema(), other.address);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.employeeCount)) {
        this.employeeCount = data().deepCopy(fields()[5].schema(), other.employeeCount);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.revenue)) {
        this.revenue = data().deepCopy(fields()[6].schema(), other.revenue);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[7].schema(), other.updatedAt);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'companyId' field.
      * Required - partition key
      * @return The value.
      */
    public java.lang.String getCompanyId() {
      return companyId;
    }


    /**
      * Sets the value of the 'companyId' field.
      * Required - partition key
      * @param value The value of 'companyId'.
      * @return This builder.
      */
    public schema.avro.AvroCompany.Builder setCompanyId(java.lang.String value) {
      validate(fields()[0], value);
      this.companyId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'companyId' field has been set.
      * Required - partition key
      * @return True if the 'companyId' field has been set, false otherwise.
      */
    public boolean hasCompanyId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'companyId' field.
      * Required - partition key
      * @return This builder.
      */
    public schema.avro.AvroCompany.Builder clearCompanyId() {
      companyId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * Required
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * Required
      * @param value The value of 'name'.
      * @return This builder.
      */
    public schema.avro.AvroCompany.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * Required
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * Required
      * @return This builder.
      */
    public schema.avro.AvroCompany.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'industry' field.
      * Required
      * @return The value.
      */
    public schema.avro.Industry getIndustry() {
      return industry;
    }


    /**
      * Sets the value of the 'industry' field.
      * Required
      * @param value The value of 'industry'.
      * @return This builder.
      */
    public schema.avro.AvroCompany.Builder setIndustry(schema.avro.Industry value) {
      validate(fields()[2], value);
      this.industry = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'industry' field has been set.
      * Required
      * @return True if the 'industry' field has been set, false otherwise.
      */
    public boolean hasIndustry() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'industry' field.
      * Required
      * @return This builder.
      */
    public schema.avro.AvroCompany.Builder clearIndustry() {
      industry = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'country' field.
      * Required
      * @return The value.
      */
    public schema.avro.Country getCountry() {
      return country;
    }


    /**
      * Sets the value of the 'country' field.
      * Required
      * @param value The value of 'country'.
      * @return This builder.
      */
    public schema.avro.AvroCompany.Builder setCountry(schema.avro.Country value) {
      validate(fields()[3], value);
      this.country = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'country' field has been set.
      * Required
      * @return True if the 'country' field has been set, false otherwise.
      */
    public boolean hasCountry() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'country' field.
      * Required
      * @return This builder.
      */
    public schema.avro.AvroCompany.Builder clearCountry() {
      country = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'address' field.
      * Optional
      * @return The value.
      */
    public java.lang.String getAddress() {
      return address;
    }


    /**
      * Sets the value of the 'address' field.
      * Optional
      * @param value The value of 'address'.
      * @return This builder.
      */
    public schema.avro.AvroCompany.Builder setAddress(java.lang.String value) {
      validate(fields()[4], value);
      this.address = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'address' field has been set.
      * Optional
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'address' field.
      * Optional
      * @return This builder.
      */
    public schema.avro.AvroCompany.Builder clearAddress() {
      address = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'employeeCount' field.
      * Optional - not all integrations provide this
      * @return The value.
      */
    public java.lang.Integer getEmployeeCount() {
      return employeeCount;
    }


    /**
      * Sets the value of the 'employeeCount' field.
      * Optional - not all integrations provide this
      * @param value The value of 'employeeCount'.
      * @return This builder.
      */
    public schema.avro.AvroCompany.Builder setEmployeeCount(java.lang.Integer value) {
      validate(fields()[5], value);
      this.employeeCount = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'employeeCount' field has been set.
      * Optional - not all integrations provide this
      * @return True if the 'employeeCount' field has been set, false otherwise.
      */
    public boolean hasEmployeeCount() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'employeeCount' field.
      * Optional - not all integrations provide this
      * @return This builder.
      */
    public schema.avro.AvroCompany.Builder clearEmployeeCount() {
      employeeCount = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'revenue' field.
      * Optional
      * @return The value.
      */
    public java.lang.Double getRevenue() {
      return revenue;
    }


    /**
      * Sets the value of the 'revenue' field.
      * Optional
      * @param value The value of 'revenue'.
      * @return This builder.
      */
    public schema.avro.AvroCompany.Builder setRevenue(java.lang.Double value) {
      validate(fields()[6], value);
      this.revenue = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'revenue' field has been set.
      * Optional
      * @return True if the 'revenue' field has been set, false otherwise.
      */
    public boolean hasRevenue() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'revenue' field.
      * Optional
      * @return This builder.
      */
    public schema.avro.AvroCompany.Builder clearRevenue() {
      revenue = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'updatedAt' field.
      * Required - epoch millis
      * @return The value.
      */
    public long getUpdatedAt() {
      return updatedAt;
    }


    /**
      * Sets the value of the 'updatedAt' field.
      * Required - epoch millis
      * @param value The value of 'updatedAt'.
      * @return This builder.
      */
    public schema.avro.AvroCompany.Builder setUpdatedAt(long value) {
      validate(fields()[7], value);
      this.updatedAt = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'updatedAt' field has been set.
      * Required - epoch millis
      * @return True if the 'updatedAt' field has been set, false otherwise.
      */
    public boolean hasUpdatedAt() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'updatedAt' field.
      * Required - epoch millis
      * @return This builder.
      */
    public schema.avro.AvroCompany.Builder clearUpdatedAt() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroCompany build() {
      try {
        AvroCompany record = new AvroCompany();
        record.companyId = fieldSetFlags()[0] ? this.companyId : (java.lang.String) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        record.industry = fieldSetFlags()[2] ? this.industry : (schema.avro.Industry) defaultValue(fields()[2]);
        record.country = fieldSetFlags()[3] ? this.country : (schema.avro.Country) defaultValue(fields()[3]);
        record.address = fieldSetFlags()[4] ? this.address : (java.lang.String) defaultValue(fields()[4]);
        record.employeeCount = fieldSetFlags()[5] ? this.employeeCount : (java.lang.Integer) defaultValue(fields()[5]);
        record.revenue = fieldSetFlags()[6] ? this.revenue : (java.lang.Double) defaultValue(fields()[6]);
        record.updatedAt = fieldSetFlags()[7] ? this.updatedAt : (java.lang.Long) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroCompany>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroCompany>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroCompany>
    READER$ = (org.apache.avro.io.DatumReader<AvroCompany>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.companyId);

    out.writeString(this.name);

    out.writeEnum(this.industry.ordinal());

    out.writeEnum(this.country.ordinal());

    if (this.address == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.address);
    }

    if (this.employeeCount == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.employeeCount);
    }

    if (this.revenue == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.revenue);
    }

    out.writeLong(this.updatedAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.companyId = in.readString();

      this.name = in.readString();

      this.industry = schema.avro.Industry.values()[in.readEnum()];

      this.country = schema.avro.Country.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.address = null;
      } else {
        this.address = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.employeeCount = null;
      } else {
        this.employeeCount = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.revenue = null;
      } else {
        this.revenue = in.readDouble();
      }

      this.updatedAt = in.readLong();

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.companyId = in.readString();
          break;

        case 1:
          this.name = in.readString();
          break;

        case 2:
          this.industry = schema.avro.Industry.values()[in.readEnum()];
          break;

        case 3:
          this.country = schema.avro.Country.values()[in.readEnum()];
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.address = null;
          } else {
            this.address = in.readString();
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.employeeCount = null;
          } else {
            this.employeeCount = in.readInt();
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.revenue = null;
          } else {
            this.revenue = in.readDouble();
          }
          break;

        case 7:
          this.updatedAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










