/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package schema.avro;
@org.apache.avro.specific.AvroGenerated
public enum Industry implements org.apache.avro.generic.GenericEnumSymbol<Industry> {
  TECH, FINANCE, HEALTH, OTHER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Industry\",\"namespace\":\"schema.avro\",\"symbols\":[\"TECH\",\"FINANCE\",\"HEALTH\",\"OTHER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
