/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package schema.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroUser extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6656669062926050145L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroUser\",\"namespace\":\"schema.avro\",\"fields\":[{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Required - partition key\"},{\"name\":\"companyId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Required - links to company partition key\"},{\"name\":\"firstName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Required\"},{\"name\":\"lastName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Required\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"UserStatus\",\"symbols\":[\"ACTIVE\",\"INACTIVE\",\"TERMINATED\",\"ON_LEAVE\"]},\"doc\":\"Required - user employment status\"},{\"name\":\"country\",\"type\":{\"type\":\"enum\",\"name\":\"Country\",\"symbols\":[\"IN\",\"US\",\"UK\",\"OTHER\"]},\"doc\":\"Required - for data locality and routing\"},{\"name\":\"department\",\"type\":{\"type\":\"enum\",\"name\":\"Department\",\"symbols\":[\"ENGINEERING\",\"SALES\",\"HR\",\"FINANCE\",\"OPERATIONS\",\"OTHER\"]},\"doc\":\"Required - routing field\"},{\"name\":\"active\",\"type\":\"boolean\",\"doc\":\"Required - quick filter flag\"},{\"name\":\"createdAt\",\"type\":\"long\",\"doc\":\"Required - epoch millis\"},{\"name\":\"age\",\"type\":[\"null\",\"int\"],\"doc\":\"Optional - not always available from HR systems\",\"default\":null},{\"name\":\"salary\",\"type\":[\"null\",\"double\"],\"doc\":\"Optional - sensitive data, may be excluded\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroUser> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroUser> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroUser> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroUser> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroUser> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroUser to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroUser from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroUser instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroUser fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Required - partition key */
  private java.lang.String userId;
  /** Required - links to company partition key */
  private java.lang.String companyId;
  /** Required */
  private java.lang.String firstName;
  /** Required */
  private java.lang.String lastName;
  /** Required - user employment status */
  private schema.avro.UserStatus status;
  /** Required - for data locality and routing */
  private schema.avro.Country country;
  /** Required - routing field */
  private schema.avro.Department department;
  /** Required - quick filter flag */
  private boolean active;
  /** Required - epoch millis */
  private long createdAt;
  /** Optional - not always available from HR systems */
  private java.lang.Integer age;
  /** Optional - sensitive data, may be excluded */
  private java.lang.Double salary;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroUser() {}

  /**
   * All-args constructor.
   * @param userId Required - partition key
   * @param companyId Required - links to company partition key
   * @param firstName Required
   * @param lastName Required
   * @param status Required - user employment status
   * @param country Required - for data locality and routing
   * @param department Required - routing field
   * @param active Required - quick filter flag
   * @param createdAt Required - epoch millis
   * @param age Optional - not always available from HR systems
   * @param salary Optional - sensitive data, may be excluded
   */
  public AvroUser(java.lang.String userId, java.lang.String companyId, java.lang.String firstName, java.lang.String lastName, schema.avro.UserStatus status, schema.avro.Country country, schema.avro.Department department, java.lang.Boolean active, java.lang.Long createdAt, java.lang.Integer age, java.lang.Double salary) {
    this.userId = userId;
    this.companyId = companyId;
    this.firstName = firstName;
    this.lastName = lastName;
    this.status = status;
    this.country = country;
    this.department = department;
    this.active = active;
    this.createdAt = createdAt;
    this.age = age;
    this.salary = salary;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return companyId;
    case 2: return firstName;
    case 3: return lastName;
    case 4: return status;
    case 5: return country;
    case 6: return department;
    case 7: return active;
    case 8: return createdAt;
    case 9: return age;
    case 10: return salary;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = value$ != null ? value$.toString() : null; break;
    case 1: companyId = value$ != null ? value$.toString() : null; break;
    case 2: firstName = value$ != null ? value$.toString() : null; break;
    case 3: lastName = value$ != null ? value$.toString() : null; break;
    case 4: status = (schema.avro.UserStatus)value$; break;
    case 5: country = (schema.avro.Country)value$; break;
    case 6: department = (schema.avro.Department)value$; break;
    case 7: active = (java.lang.Boolean)value$; break;
    case 8: createdAt = (java.lang.Long)value$; break;
    case 9: age = (java.lang.Integer)value$; break;
    case 10: salary = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return Required - partition key
   */
  public java.lang.String getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * Required - partition key
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'companyId' field.
   * @return Required - links to company partition key
   */
  public java.lang.String getCompanyId() {
    return companyId;
  }


  /**
   * Sets the value of the 'companyId' field.
   * Required - links to company partition key
   * @param value the value to set.
   */
  public void setCompanyId(java.lang.String value) {
    this.companyId = value;
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return Required
   */
  public java.lang.String getFirstName() {
    return firstName;
  }


  /**
   * Sets the value of the 'firstName' field.
   * Required
   * @param value the value to set.
   */
  public void setFirstName(java.lang.String value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return Required
   */
  public java.lang.String getLastName() {
    return lastName;
  }


  /**
   * Sets the value of the 'lastName' field.
   * Required
   * @param value the value to set.
   */
  public void setLastName(java.lang.String value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return Required - user employment status
   */
  public schema.avro.UserStatus getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * Required - user employment status
   * @param value the value to set.
   */
  public void setStatus(schema.avro.UserStatus value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'country' field.
   * @return Required - for data locality and routing
   */
  public schema.avro.Country getCountry() {
    return country;
  }


  /**
   * Sets the value of the 'country' field.
   * Required - for data locality and routing
   * @param value the value to set.
   */
  public void setCountry(schema.avro.Country value) {
    this.country = value;
  }

  /**
   * Gets the value of the 'department' field.
   * @return Required - routing field
   */
  public schema.avro.Department getDepartment() {
    return department;
  }


  /**
   * Sets the value of the 'department' field.
   * Required - routing field
   * @param value the value to set.
   */
  public void setDepartment(schema.avro.Department value) {
    this.department = value;
  }

  /**
   * Gets the value of the 'active' field.
   * @return Required - quick filter flag
   */
  public boolean getActive() {
    return active;
  }


  /**
   * Sets the value of the 'active' field.
   * Required - quick filter flag
   * @param value the value to set.
   */
  public void setActive(boolean value) {
    this.active = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return Required - epoch millis
   */
  public long getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * Required - epoch millis
   * @param value the value to set.
   */
  public void setCreatedAt(long value) {
    this.createdAt = value;
  }

  /**
   * Gets the value of the 'age' field.
   * @return Optional - not always available from HR systems
   */
  public java.lang.Integer getAge() {
    return age;
  }


  /**
   * Sets the value of the 'age' field.
   * Optional - not always available from HR systems
   * @param value the value to set.
   */
  public void setAge(java.lang.Integer value) {
    this.age = value;
  }

  /**
   * Gets the value of the 'salary' field.
   * @return Optional - sensitive data, may be excluded
   */
  public java.lang.Double getSalary() {
    return salary;
  }


  /**
   * Sets the value of the 'salary' field.
   * Optional - sensitive data, may be excluded
   * @param value the value to set.
   */
  public void setSalary(java.lang.Double value) {
    this.salary = value;
  }

  /**
   * Creates a new AvroUser RecordBuilder.
   * @return A new AvroUser RecordBuilder
   */
  public static schema.avro.AvroUser.Builder newBuilder() {
    return new schema.avro.AvroUser.Builder();
  }

  /**
   * Creates a new AvroUser RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroUser RecordBuilder
   */
  public static schema.avro.AvroUser.Builder newBuilder(schema.avro.AvroUser.Builder other) {
    if (other == null) {
      return new schema.avro.AvroUser.Builder();
    } else {
      return new schema.avro.AvroUser.Builder(other);
    }
  }

  /**
   * Creates a new AvroUser RecordBuilder by copying an existing AvroUser instance.
   * @param other The existing instance to copy.
   * @return A new AvroUser RecordBuilder
   */
  public static schema.avro.AvroUser.Builder newBuilder(schema.avro.AvroUser other) {
    if (other == null) {
      return new schema.avro.AvroUser.Builder();
    } else {
      return new schema.avro.AvroUser.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroUser instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroUser>
    implements org.apache.avro.data.RecordBuilder<AvroUser> {

    /** Required - partition key */
    private java.lang.String userId;
    /** Required - links to company partition key */
    private java.lang.String companyId;
    /** Required */
    private java.lang.String firstName;
    /** Required */
    private java.lang.String lastName;
    /** Required - user employment status */
    private schema.avro.UserStatus status;
    /** Required - for data locality and routing */
    private schema.avro.Country country;
    /** Required - routing field */
    private schema.avro.Department department;
    /** Required - quick filter flag */
    private boolean active;
    /** Required - epoch millis */
    private long createdAt;
    /** Optional - not always available from HR systems */
    private java.lang.Integer age;
    /** Optional - sensitive data, may be excluded */
    private java.lang.Double salary;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(schema.avro.AvroUser.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.companyId)) {
        this.companyId = data().deepCopy(fields()[1].schema(), other.companyId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.firstName)) {
        this.firstName = data().deepCopy(fields()[2].schema(), other.firstName);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.lastName)) {
        this.lastName = data().deepCopy(fields()[3].schema(), other.lastName);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.country)) {
        this.country = data().deepCopy(fields()[5].schema(), other.country);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.department)) {
        this.department = data().deepCopy(fields()[6].schema(), other.department);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.active)) {
        this.active = data().deepCopy(fields()[7].schema(), other.active);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[8].schema(), other.createdAt);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.age)) {
        this.age = data().deepCopy(fields()[9].schema(), other.age);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.salary)) {
        this.salary = data().deepCopy(fields()[10].schema(), other.salary);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroUser instance
     * @param other The existing instance to copy.
     */
    private Builder(schema.avro.AvroUser other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.companyId)) {
        this.companyId = data().deepCopy(fields()[1].schema(), other.companyId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.firstName)) {
        this.firstName = data().deepCopy(fields()[2].schema(), other.firstName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lastName)) {
        this.lastName = data().deepCopy(fields()[3].schema(), other.lastName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.country)) {
        this.country = data().deepCopy(fields()[5].schema(), other.country);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.department)) {
        this.department = data().deepCopy(fields()[6].schema(), other.department);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.active)) {
        this.active = data().deepCopy(fields()[7].schema(), other.active);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[8].schema(), other.createdAt);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.age)) {
        this.age = data().deepCopy(fields()[9].schema(), other.age);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.salary)) {
        this.salary = data().deepCopy(fields()[10].schema(), other.salary);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * Required - partition key
      * @return The value.
      */
    public java.lang.String getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * Required - partition key
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder setUserId(java.lang.String value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * Required - partition key
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * Required - partition key
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'companyId' field.
      * Required - links to company partition key
      * @return The value.
      */
    public java.lang.String getCompanyId() {
      return companyId;
    }


    /**
      * Sets the value of the 'companyId' field.
      * Required - links to company partition key
      * @param value The value of 'companyId'.
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder setCompanyId(java.lang.String value) {
      validate(fields()[1], value);
      this.companyId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'companyId' field has been set.
      * Required - links to company partition key
      * @return True if the 'companyId' field has been set, false otherwise.
      */
    public boolean hasCompanyId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'companyId' field.
      * Required - links to company partition key
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder clearCompanyId() {
      companyId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'firstName' field.
      * Required
      * @return The value.
      */
    public java.lang.String getFirstName() {
      return firstName;
    }


    /**
      * Sets the value of the 'firstName' field.
      * Required
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder setFirstName(java.lang.String value) {
      validate(fields()[2], value);
      this.firstName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * Required
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'firstName' field.
      * Required
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * Required
      * @return The value.
      */
    public java.lang.String getLastName() {
      return lastName;
    }


    /**
      * Sets the value of the 'lastName' field.
      * Required
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder setLastName(java.lang.String value) {
      validate(fields()[3], value);
      this.lastName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * Required
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'lastName' field.
      * Required
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * Required - user employment status
      * @return The value.
      */
    public schema.avro.UserStatus getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * Required - user employment status
      * @param value The value of 'status'.
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder setStatus(schema.avro.UserStatus value) {
      validate(fields()[4], value);
      this.status = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * Required - user employment status
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'status' field.
      * Required - user employment status
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder clearStatus() {
      status = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'country' field.
      * Required - for data locality and routing
      * @return The value.
      */
    public schema.avro.Country getCountry() {
      return country;
    }


    /**
      * Sets the value of the 'country' field.
      * Required - for data locality and routing
      * @param value The value of 'country'.
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder setCountry(schema.avro.Country value) {
      validate(fields()[5], value);
      this.country = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'country' field has been set.
      * Required - for data locality and routing
      * @return True if the 'country' field has been set, false otherwise.
      */
    public boolean hasCountry() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'country' field.
      * Required - for data locality and routing
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder clearCountry() {
      country = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'department' field.
      * Required - routing field
      * @return The value.
      */
    public schema.avro.Department getDepartment() {
      return department;
    }


    /**
      * Sets the value of the 'department' field.
      * Required - routing field
      * @param value The value of 'department'.
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder setDepartment(schema.avro.Department value) {
      validate(fields()[6], value);
      this.department = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'department' field has been set.
      * Required - routing field
      * @return True if the 'department' field has been set, false otherwise.
      */
    public boolean hasDepartment() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'department' field.
      * Required - routing field
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder clearDepartment() {
      department = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'active' field.
      * Required - quick filter flag
      * @return The value.
      */
    public boolean getActive() {
      return active;
    }


    /**
      * Sets the value of the 'active' field.
      * Required - quick filter flag
      * @param value The value of 'active'.
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder setActive(boolean value) {
      validate(fields()[7], value);
      this.active = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'active' field has been set.
      * Required - quick filter flag
      * @return True if the 'active' field has been set, false otherwise.
      */
    public boolean hasActive() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'active' field.
      * Required - quick filter flag
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder clearActive() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * Required - epoch millis
      * @return The value.
      */
    public long getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * Required - epoch millis
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder setCreatedAt(long value) {
      validate(fields()[8], value);
      this.createdAt = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * Required - epoch millis
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * Required - epoch millis
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder clearCreatedAt() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * Optional - not always available from HR systems
      * @return The value.
      */
    public java.lang.Integer getAge() {
      return age;
    }


    /**
      * Sets the value of the 'age' field.
      * Optional - not always available from HR systems
      * @param value The value of 'age'.
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder setAge(java.lang.Integer value) {
      validate(fields()[9], value);
      this.age = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * Optional - not always available from HR systems
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'age' field.
      * Optional - not always available from HR systems
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder clearAge() {
      age = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'salary' field.
      * Optional - sensitive data, may be excluded
      * @return The value.
      */
    public java.lang.Double getSalary() {
      return salary;
    }


    /**
      * Sets the value of the 'salary' field.
      * Optional - sensitive data, may be excluded
      * @param value The value of 'salary'.
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder setSalary(java.lang.Double value) {
      validate(fields()[10], value);
      this.salary = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'salary' field has been set.
      * Optional - sensitive data, may be excluded
      * @return True if the 'salary' field has been set, false otherwise.
      */
    public boolean hasSalary() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'salary' field.
      * Optional - sensitive data, may be excluded
      * @return This builder.
      */
    public schema.avro.AvroUser.Builder clearSalary() {
      salary = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroUser build() {
      try {
        AvroUser record = new AvroUser();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.String) defaultValue(fields()[0]);
        record.companyId = fieldSetFlags()[1] ? this.companyId : (java.lang.String) defaultValue(fields()[1]);
        record.firstName = fieldSetFlags()[2] ? this.firstName : (java.lang.String) defaultValue(fields()[2]);
        record.lastName = fieldSetFlags()[3] ? this.lastName : (java.lang.String) defaultValue(fields()[3]);
        record.status = fieldSetFlags()[4] ? this.status : (schema.avro.UserStatus) defaultValue(fields()[4]);
        record.country = fieldSetFlags()[5] ? this.country : (schema.avro.Country) defaultValue(fields()[5]);
        record.department = fieldSetFlags()[6] ? this.department : (schema.avro.Department) defaultValue(fields()[6]);
        record.active = fieldSetFlags()[7] ? this.active : (java.lang.Boolean) defaultValue(fields()[7]);
        record.createdAt = fieldSetFlags()[8] ? this.createdAt : (java.lang.Long) defaultValue(fields()[8]);
        record.age = fieldSetFlags()[9] ? this.age : (java.lang.Integer) defaultValue(fields()[9]);
        record.salary = fieldSetFlags()[10] ? this.salary : (java.lang.Double) defaultValue(fields()[10]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroUser>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroUser>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroUser>
    READER$ = (org.apache.avro.io.DatumReader<AvroUser>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.userId);

    out.writeString(this.companyId);

    out.writeString(this.firstName);

    out.writeString(this.lastName);

    out.writeEnum(this.status.ordinal());

    out.writeEnum(this.country.ordinal());

    out.writeEnum(this.department.ordinal());

    out.writeBoolean(this.active);

    out.writeLong(this.createdAt);

    if (this.age == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.age);
    }

    if (this.salary == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.salary);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readString();

      this.companyId = in.readString();

      this.firstName = in.readString();

      this.lastName = in.readString();

      this.status = schema.avro.UserStatus.values()[in.readEnum()];

      this.country = schema.avro.Country.values()[in.readEnum()];

      this.department = schema.avro.Department.values()[in.readEnum()];

      this.active = in.readBoolean();

      this.createdAt = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.age = null;
      } else {
        this.age = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.salary = null;
      } else {
        this.salary = in.readDouble();
      }

    } else {
      for (int i = 0; i < 11; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readString();
          break;

        case 1:
          this.companyId = in.readString();
          break;

        case 2:
          this.firstName = in.readString();
          break;

        case 3:
          this.lastName = in.readString();
          break;

        case 4:
          this.status = schema.avro.UserStatus.values()[in.readEnum()];
          break;

        case 5:
          this.country = schema.avro.Country.values()[in.readEnum()];
          break;

        case 6:
          this.department = schema.avro.Department.values()[in.readEnum()];
          break;

        case 7:
          this.active = in.readBoolean();
          break;

        case 8:
          this.createdAt = in.readLong();
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.age = null;
          } else {
            this.age = in.readInt();
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.salary = null;
          } else {
            this.salary = in.readDouble();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










