/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package schema.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroTemperatureSensor extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3693243249359522484L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroTemperatureSensor\",\"namespace\":\"schema.avro\",\"fields\":[{\"name\":\"sensorId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"temp\",\"type\":\"int\"},{\"name\":\"createdTime\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroTemperatureSensor> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroTemperatureSensor> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroTemperatureSensor> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroTemperatureSensor> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroTemperatureSensor> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroTemperatureSensor to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroTemperatureSensor from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroTemperatureSensor instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroTemperatureSensor fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String sensorId;
  private int temp;
  private long createdTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroTemperatureSensor() {}

  /**
   * All-args constructor.
   * @param sensorId The new value for sensorId
   * @param temp The new value for temp
   * @param createdTime The new value for createdTime
   */
  public AvroTemperatureSensor(java.lang.String sensorId, java.lang.Integer temp, java.lang.Long createdTime) {
    this.sensorId = sensorId;
    this.temp = temp;
    this.createdTime = createdTime;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sensorId;
    case 1: return temp;
    case 2: return createdTime;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sensorId = value$ != null ? value$.toString() : null; break;
    case 1: temp = (java.lang.Integer)value$; break;
    case 2: createdTime = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sensorId' field.
   * @return The value of the 'sensorId' field.
   */
  public java.lang.String getSensorId() {
    return sensorId;
  }


  /**
   * Sets the value of the 'sensorId' field.
   * @param value the value to set.
   */
  public void setSensorId(java.lang.String value) {
    this.sensorId = value;
  }

  /**
   * Gets the value of the 'temp' field.
   * @return The value of the 'temp' field.
   */
  public int getTemp() {
    return temp;
  }


  /**
   * Sets the value of the 'temp' field.
   * @param value the value to set.
   */
  public void setTemp(int value) {
    this.temp = value;
  }

  /**
   * Gets the value of the 'createdTime' field.
   * @return The value of the 'createdTime' field.
   */
  public long getCreatedTime() {
    return createdTime;
  }


  /**
   * Sets the value of the 'createdTime' field.
   * @param value the value to set.
   */
  public void setCreatedTime(long value) {
    this.createdTime = value;
  }

  /**
   * Creates a new AvroTemperatureSensor RecordBuilder.
   * @return A new AvroTemperatureSensor RecordBuilder
   */
  public static schema.avro.AvroTemperatureSensor.Builder newBuilder() {
    return new schema.avro.AvroTemperatureSensor.Builder();
  }

  /**
   * Creates a new AvroTemperatureSensor RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroTemperatureSensor RecordBuilder
   */
  public static schema.avro.AvroTemperatureSensor.Builder newBuilder(schema.avro.AvroTemperatureSensor.Builder other) {
    if (other == null) {
      return new schema.avro.AvroTemperatureSensor.Builder();
    } else {
      return new schema.avro.AvroTemperatureSensor.Builder(other);
    }
  }

  /**
   * Creates a new AvroTemperatureSensor RecordBuilder by copying an existing AvroTemperatureSensor instance.
   * @param other The existing instance to copy.
   * @return A new AvroTemperatureSensor RecordBuilder
   */
  public static schema.avro.AvroTemperatureSensor.Builder newBuilder(schema.avro.AvroTemperatureSensor other) {
    if (other == null) {
      return new schema.avro.AvroTemperatureSensor.Builder();
    } else {
      return new schema.avro.AvroTemperatureSensor.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroTemperatureSensor instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroTemperatureSensor>
    implements org.apache.avro.data.RecordBuilder<AvroTemperatureSensor> {

    private java.lang.String sensorId;
    private int temp;
    private long createdTime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(schema.avro.AvroTemperatureSensor.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sensorId)) {
        this.sensorId = data().deepCopy(fields()[0].schema(), other.sensorId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.temp)) {
        this.temp = data().deepCopy(fields()[1].schema(), other.temp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.createdTime)) {
        this.createdTime = data().deepCopy(fields()[2].schema(), other.createdTime);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroTemperatureSensor instance
     * @param other The existing instance to copy.
     */
    private Builder(schema.avro.AvroTemperatureSensor other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.sensorId)) {
        this.sensorId = data().deepCopy(fields()[0].schema(), other.sensorId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.temp)) {
        this.temp = data().deepCopy(fields()[1].schema(), other.temp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.createdTime)) {
        this.createdTime = data().deepCopy(fields()[2].schema(), other.createdTime);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'sensorId' field.
      * @return The value.
      */
    public java.lang.String getSensorId() {
      return sensorId;
    }


    /**
      * Sets the value of the 'sensorId' field.
      * @param value The value of 'sensorId'.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureSensor.Builder setSensorId(java.lang.String value) {
      validate(fields()[0], value);
      this.sensorId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sensorId' field has been set.
      * @return True if the 'sensorId' field has been set, false otherwise.
      */
    public boolean hasSensorId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sensorId' field.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureSensor.Builder clearSensorId() {
      sensorId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'temp' field.
      * @return The value.
      */
    public int getTemp() {
      return temp;
    }


    /**
      * Sets the value of the 'temp' field.
      * @param value The value of 'temp'.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureSensor.Builder setTemp(int value) {
      validate(fields()[1], value);
      this.temp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'temp' field has been set.
      * @return True if the 'temp' field has been set, false otherwise.
      */
    public boolean hasTemp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'temp' field.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureSensor.Builder clearTemp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdTime' field.
      * @return The value.
      */
    public long getCreatedTime() {
      return createdTime;
    }


    /**
      * Sets the value of the 'createdTime' field.
      * @param value The value of 'createdTime'.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureSensor.Builder setCreatedTime(long value) {
      validate(fields()[2], value);
      this.createdTime = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'createdTime' field has been set.
      * @return True if the 'createdTime' field has been set, false otherwise.
      */
    public boolean hasCreatedTime() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'createdTime' field.
      * @return This builder.
      */
    public schema.avro.AvroTemperatureSensor.Builder clearCreatedTime() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroTemperatureSensor build() {
      try {
        AvroTemperatureSensor record = new AvroTemperatureSensor();
        record.sensorId = fieldSetFlags()[0] ? this.sensorId : (java.lang.String) defaultValue(fields()[0]);
        record.temp = fieldSetFlags()[1] ? this.temp : (java.lang.Integer) defaultValue(fields()[1]);
        record.createdTime = fieldSetFlags()[2] ? this.createdTime : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroTemperatureSensor>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroTemperatureSensor>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroTemperatureSensor>
    READER$ = (org.apache.avro.io.DatumReader<AvroTemperatureSensor>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.sensorId);

    out.writeInt(this.temp);

    out.writeLong(this.createdTime);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.sensorId = in.readString();

      this.temp = in.readInt();

      this.createdTime = in.readLong();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.sensorId = in.readString();
          break;

        case 1:
          this.temp = in.readInt();
          break;

        case 2:
          this.createdTime = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










