/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package schema.avro;
@org.apache.avro.specific.AvroGenerated
public enum Country implements org.apache.avro.generic.GenericEnumSymbol<Country> {
  IN, US, UK, OTHER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Country\",\"namespace\":\"schema.avro\",\"symbols\":[\"IN\",\"US\",\"UK\",\"OTHER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
