/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package schema.avro;
@org.apache.avro.specific.AvroGenerated
public enum Department implements org.apache.avro.generic.GenericEnumSymbol<Department> {
  ENGINEERING, SALES, HR, FINANCE, OPERATIONS, OTHER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Department\",\"namespace\":\"schema.avro\",\"symbols\":[\"ENGINEERING\",\"SALES\",\"HR\",\"FINANCE\",\"OPERATIONS\",\"OTHER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
